title: 'Pretoria Farms'
default_lang: en
author:
  name: 'SDCO Partners'
  email: asif@sdcopartners.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Pretoia Farms : Brewers & Farmers working together'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
